// ***********************************************************************************
//   Custom DPA Handler code example - User peripheral implementation - i2c          *
// ***********************************************************************************
//
// Code was originally written by IQRF Tech s.r.o.
// Changes are made by Simen Stensås and Kjell Kirkaune, for ELE3391 Elektro prosjekt in the fall of 2019 at NTNU in Gjøvik.
// The unchanged version of this code can be found at downloaded IQRF resources folder (downloaded at IQRF's website as .zip).
//
// Code tested on: TR-72DA, on OS 4.03 and DPA 4.03. No guarantee to work on future versions, minor changes may be done.
//
// *********************************************************************


//############################################################################################


// Default IQRF include (modify the path according to your setup)
#include "folder\to\IQRF.h"

// Default DPA header (modify the path according to your setup)
#include "folder\to\DPA.h"
// Default Custom DPA Handler header (modify the path according to your setup)
#include "folder\to\DPAcustomHandler.h"

#define I2C_ADDRESS    0x90


//############################################################################################

void i2c_init();
void i2c_shutdown();
void i2c_waitForIdle();
void i2c_start();
void i2c_repStart();
void i2c_stop();
uns8 i2c_read( bit ack );
uns8 i2c_write( uns8 i2cWriteData );
void Write(uns8 reg_addr, uns8 _data);
uns8 Read8(uns8 reg_addr);
uns16 Read16(uns8 reg_addr);

// Must be the 1st defined function in the source code in order to be placed at the correct FLASH location!
//############################################################################################
bit CustomDpaHandler()
//############################################################################################
{
  // Handler presence mark
  clrwdt();

  // Detect DPA event to handle
  switch ( GetDpaEvent() )
  {
    // -------------------------------------------------
    case DpaEvent_Interrupt:
      // Do an extra quick background interrupt work
      // ! The time spent handling this event is critical.If there is no interrupt to handle return immediately otherwise keep the code as fast as possible.
      // ! Make sure the event is the 1st case in the main switch statement at the handler routine.This ensures that the event is handled as the 1st one.
      // ! It is desirable that this event is handled with immediate return even if it is not used by the custom handler because the Interrupt event is raised on every MCU interrupt and the “empty” return handler ensures the shortest possible interrupt routine response time.
      // ! Only global variables or local ones marked by static keyword can be used to allow reentrancy.
      // ! Make sure race condition does not occur when accessing those variables at other places.
      // ! Make sure( inspect.lst file generated by C compiler ) compiler does not create any hidden temporary local variable( occurs when using division, multiplication or bit shifts ) at the event handler code.The name of such variable is usually Cnumbercnt.
      // ! Do not call any OS functions except setINDFx().
      // ! Do not use any OS variables especially for writing access.
      // ! All above rules apply also to any other function being called from the event handler code, although calling any function from Interrupt event is not recommended because of additional MCU stack usage.

DpaHandleReturnTRUE:
      return TRUE;

      // -------------------------------------------------
    case DpaEvent_Init:
      // Do a one time initialization work before main loop starts
    case DpaEvent_AfterSleep:
      // Called after woken up after sleep

      i2c_init();
      break;

      // -------------------------------------------------
    case DpaEvent_BeforeSleep:
      // Called before going to sleep

      i2c_shutdown();
      break;

      // -------------------------------------------------
    case DpaEvent_DpaRequest:
      // Called to interpret DPA request for peripherals
      // -------------------------------------------------
      // Peripheral enumeration
      if ( IsDpaEnumPeripheralsRequest() )
      {
        // We implement 1 user peripheral
        _DpaMessage.EnumPeripheralsAnswer.UserPerNr = 1;
        FlagUserPer( _DpaMessage.EnumPeripheralsAnswer.UserPer, PNUM_USER + 0 );
        _DpaMessage.EnumPeripheralsAnswer.HWPID = 0x000F;
        _DpaMessage.EnumPeripheralsAnswer.HWPIDver = 0xAbCd;

        goto DpaHandleReturnTRUE;
      }
      // -------------------------------------------------
      // Get information about peripheral
      else if ( IsDpaPeripheralInfoRequest() )
      {
        if ( _PNUM == PNUM_USER + 2 )
        {
          _DpaMessage.PeripheralInfoAnswer.PerT = PERIPHERAL_TYPE_USER_AREA;
          _DpaMessage.PeripheralInfoAnswer.PerTE = PERIPHERAL_TYPE_EXTENDED_READ;
          goto DpaHandleReturnTRUE;
        }

        break;
      }
      // -------------------------------------------------
      else
      {
        // Handle peripheral command
        if ( _PNUM == PNUM_USER + 2 )
        {
          // Check command
          switch ( _PCMD )
          {
            case 0:
              // -------------------------------------------------
              // TEST
              if ( _DpaDataLength != 0 )
                DpaApiReturnPeripheralError( ERROR_DATA_LEN );

			int16 data = Read16(0x00);
              _DpaMessage.Response.PData[0] = data.high8;
			  _DpaMessage.Response.PData[1] = data.low8;

              _DpaDataLength = 2;
			  
              goto DpaHandleReturnTRUE;

            default:
              // -------------------------------------------------
              // Invalid command
              DpaApiReturnPeripheralError( ERROR_PCMD );
          }
        }
      }
  }

  return FALSE;
}

//############################################################################################

#pragma library 1	// Compile only used functions

// *********************************************************************

void writeToSSPCON2( uns8 value @ param4.high8 )
{
  writeToRAM( &SSPCON2, value );
}
//----------------------------------------------------------------------

void writeOredToSSPCON2( uns8 value @ param4.high8 )
{
  writeToSSPCON2( SSPCON2 | value );
}

//----------------------------------------------------------------------

void i2c_init()
{
  PORTC = 0x80;                       // port

  TRISC.3 = 1;                        // SCL as input (SIM C6)
  TRISC.4 = 1;                        // SDA as input (SIM C7)

  TRISA.5 = 1;                        // sensor ALERT as input (SIM C5)
  TRISB.4 = 1;                        // shared with SIM C5
  TRISC.6 = 1;                        // shared with SIM C5

  writeToRAM( &SSPCON1, 0x38 );		  // I2C master mode     SSPCON = 0b00111000
  writeToSSPCON2( 0x00 );

  SSPADD = ( F_OSC / 50000 / 4 ) - 2; // 50 kHz SCL frequency

  SMP = 1;                            // Disable slew rate control
}

//------------------------------------------------------------------------

void i2c_shutdown()
{
  writeToRAM( &SSPCON1, 0x00 );		  // I2C master mode     SSPCON = 0
}

//------------------------------------------------------------------------
void i2c_waitForIdle()
{
  while ( SSPCON2 & 0x1F );           // Wait for idle and not writing
  while ( RW_ );                      // Wait for idle and not writing
}
//----------------------------------------------------------------------

void i2c_start()
{
  i2c_waitForIdle();
  writeOredToSSPCON2( 0x01 );		// SEN = 1
}
//----------------------------------------------------------------------

void i2c_repStart()
{
  i2c_waitForIdle();
  writeOredToSSPCON2( 0x02 );		// RSEN = 1
}
//----------------------------------------------------------------------

void i2c_stop()
{
  i2c_waitForIdle();
  writeOredToSSPCON2( 0x04 );		// PEN = 1
}
//----------------------------------------------------------------------

uns8 i2c_read( bit ack )
{
  i2c_waitForIdle();
  writeOredToSSPCON2( 0x08 );		// RCEN = 1

  i2c_waitForIdle();

  uns8 i2cReadData @ userReg0;
  i2cReadData = SSPBUF;

  i2c_waitForIdle();

  if ( ack )
    writeToSSPCON2( SSPCON2 & 0xDF ); // Acknowledge, ACKDT = 0
  else
    writeOredToSSPCON2( 0x20 );		  // Not acknowledge, ACKDT = 1 

  writeOredToSSPCON2( 0x10 );		  // Send acknowledge sequence, ACKEN = 1 
  return i2cReadData;
}
//----------------------------------------------------------------------

uns8 i2c_write(uns8 i2cWriteData)
{
    i2c_waitForIdle();
    SSPBUF = i2cWriteData;
	return(!(readFromRAM(&SSPCON2) & 0x40)); 	// returns 1 if transmission is acknowledged, return(!ACKSTAT);
}

// writes 1 byte '_data' to register 'reg_addr'
void Write(uns8 reg_addr, uns8 _data)
{
  i2c_start();
  i2c_write(I2C_ADDRESS);
  i2c_write(reg_addr);
  i2c_write(_data);
  i2c_stop();
}

// reads 8 bits from register 'reg_addr'
uns8 Read8(uns8 reg_addr)
{
  uns8 ret;

  i2c_start();
  i2c_write(I2C_ADDRESS);
  i2c_write(reg_addr);
  i2c_stop();
  
  i2c_start();
  i2c_write(I2C_ADDRESS | 1);
  ret = i2c_read( FALSE );
  i2c_stop();

  return ret;
}

// reads 16 bits from register 'reg_addr'
uns16 Read16(uns8 reg_addr)
{
  uns16 ret;

  i2c_start();
  i2c_write(I2C_ADDRESS);
  i2c_write(reg_addr);
  i2c_stop();
  
  i2c_start();
  i2c_write(I2C_ADDRESS | 1);
  ret.high8 = i2c_read( TRUE );
  ret.low8 = i2c_read( FALSE );
  i2c_stop();

  return ret;
}



// ############################################################################################
#pragma library 0	// Compile all
//############################################################################################
// Default Custom DPA Handler header; 2nd include to implement Code bumper to detect too long code of the Custom DPA Handler (modify the path according to your setup) 
#include "folder\to\DPAcustomHandler.h"
//############################################################################################
