// ***********************************************************************************
//   Custom DPA Handler code example										         *
// ***********************************************************************************
//
// Code was originally written by IQRF Tech s.r.o.
// Changes are made by Simen Stensås and Kjell Kirkaune, for ELE3391 Elektro prosjekt in the fall of 2019 at NTNU in Gjøvik.
// The unchanged version of this code can be found at downloaded IQRF resources folder (downloaded at IQRF's website as .zip).
//
// Code tested on: TR-72DA, on OS 4.03 and DPA 4.03. No guarantee to work on future versions, minor changes may be done.
//
// *********************************************************************


//############################################################################################


// Default IQRF include (modify the path according to your setup)
#include "folder\to\IQRF.h"

// Default DPA header (modify the path according to your setup)
#include "folder\to\DPA.h"
// Default Custom DPA Handler header (modify the path according to your setup)
#include "folder\to\DPAcustomHandler.h"


// C.5 = C8 = PORT1
#define	PORT1_LAT	LATC.5 
#define	PORT1_TRIS	TRISC.5


// Must be the 1st defined function in the source code in order to be placed at the correct FLASH location!
//############################################################################################
bit CustomDpaHandler()
//############################################################################################


{
  // Handler presence mark
  clrwdt();

  // Detect DPA event to handle
  switch ( GetDpaEvent() )
  {
    // -------------------------------------------------
    case DpaEvent_Interrupt:
      // Do an extra quick background interrupt work
      // ! The time spent handling this event is critical.If there is no interrupt to handle return immediately otherwise keep the code as fast as possible.
      // ! Make sure the event is the 1st case in the main switch statement at the handler routine.This ensures that the event is handled as the 1st one.
      // ! It is desirable that this event is handled with immediate return even if it is not used by the custom handler because the Interrupt event is raised on every MCU interrupt and the “empty” return handler ensures the shortest possible interrupt routine response time.
      // ! Only global variables or local ones marked by static keyword can be used to allow reentrancy.
      // ! Make sure race condition does not occur when accessing those variables at other places.
      // ! Make sure( inspect.lst file generated by C compiler ) compiler does not create any hidden temporary local variable( occurs when using division, multiplication or bit shifts ) at the event handler code.The name of such variable is usually Cnumbercnt.
      // ! Do not call any OS functions except setINDFx().
      // ! Do not use any OS variables especially for writing access.
      // ! All above rules apply also to any other function being called from the event handler code, although calling any function from Interrupt event is not recommended because of additional MCU stack usage.


      return Carry;



      // -------------------------------------------------
    case DpaEvent_DpaRequest:
    {
      // Called to interpret DPA request for peripherals
      // -------------------------------------------------
      // Peripheral enumeration
      if ( IsDpaEnumPeripheralsRequest() )
      {
        // We implement 1 user peripheral
        _DpaMessage.EnumPeripheralsAnswer.UserPerNr = 1;
#ifdef FlagUserPer	// Get ready for upcoming DPA 3.00
        FlagUserPer( _DpaMessage.EnumPeripheralsAnswer.UserPer, PNUM_USER + 0 );
#endif
        _DpaMessage.EnumPeripheralsAnswer.HWPID = ThisHWPID;
        _DpaMessage.EnumPeripheralsAnswer.HWPIDver = 0x0000;

DpaHandleReturnTRUE:
        return TRUE;
      }
      // -------------------------------------------------
      // Get information about peripheral
      else if ( IsDpaPeripheralInfoRequest() )
      {
        if ( _PNUM == PNUM_USER + 2 )
        {
          _DpaMessage.PeripheralInfoAnswer.PerT = PERIPHERAL_TYPE_USER_AREA;
#if !defined( DDC_RE_01 )
          _DpaMessage.PeripheralInfoAnswer.PerTE = PERIPHERAL_TYPE_EXTENDED_READ;
#else
          _DpaMessage.PeripheralInfoAnswer.PerTE = PERIPHERAL_TYPE_EXTENDED_READ_WRITE;
#endif
          goto DpaHandleReturnTRUE;
        }

        break;
      }
      // -------------------------------------------------
      else
      {
        // Handle peripheral command
        if ( _PNUM == PNUM_USER + 2 )
        {
          switch ( _PCMD )
          {
            case 0x00:
              // Control and return state of relays
              if ( _DpaDataLength != 1 )
                DpaApiReturnPeripheralError( ERROR_DATA_LEN );

              // PORT#1
              // Get
              userReg0 = 0;
              if ( PORT1_LAT )
                userReg0.0 = 1;

              // Set
              switch ( _DpaMessage.Request.PData[0] )
              {
                case 0:
                  PORT1_LAT = 0;
                  break;
                case 1:
                  PORT1_LAT = 1;
                  break;
              }
              _DpaMessage.Response.PData[0] = userReg0;

              goto DpaHandleReturnTRUE;

              // Invalid command
            default:
              DpaApiReturnPeripheralError( ERROR_PCMD );
              break;
          }
        }
      }

      break;
    }

    // -------------------------------------------------
    case DpaEvent_Init:

      // Initialize relays
      PORT1_LAT = 0;
      PORT1_TRIS = 0;
	  
      break;
  }
  return FALSE;
}

//############################################################################################
// Default Custom DPA Handler header; 2nd include to implement Code bumper to detect too long code of the Custom DPA Handler (modify the path according to your setup) 
#include "folder\to\DPAcustomHandler.h"
//############################################################################################